name: I want to request a game
description: "Game request, for new games or updates of existing games.
Before submitting a game request, please make sure that the game you are requesting is not already in the repository.
Also, be aware that the game you are requesting must be open-source and must comply with the Code Of Conduct.

The game request will be reviewed by the maintainers and, if approved, it will be added to the repository as
a gameName-version.json or as a classic folder in the Games folder.

The main objective to add games to the repository is to provide a way to install and play games in a simple way,
without the need to download and install the game manually. Also, it provides a way to keep the games updated automatically."
title: '[Game]: '
labels:
  - game
assignees:
  - {{ github.actor }}
  - MasterLaplace
body:
  - type: input
    id: gameTitle
    attributes:
      label: What is your game title?
    validations:
      required: true
  - type: input
    id: gameVersion
    attributes:
      label: What is your game version?
    validations:
      required: true
  - type: checkboxes
    id: isUpdate
    attributes:
      label: Is it an update?
      options:
        - label: "Yes (Please provide the previous version)"
        - label: "No"
  - type: input
    id: gamePreviousVersion
    attributes:
      label: What is the previous version?
  - type: input
    id: gameAuthor
    attributes:
      label: Who is the author/editor of the game?
    validations:
      required: true
  - type: textarea
    id: gameDescription
    attributes:
      label: Please describe your game in a few words
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: I read the Code Of Conduct
      options:
        - label: "I read the Code Of Conduct and I comply to it"
          required: true
