name: Build Checker Ubuntu

on:
  push:
    branches-ignore:
     - 'ga-ignore-**'
     - 'gh-pages'

jobs:
  build_checker_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install cmake

      - name: Build
        run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
