name: Build Checker MacOs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  verify-commit-name:
    runs-on: macos-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            brew install cmake
            brew install ninja


      - name: Build
        run: |
            mkdir build
            cd build
            cmake -G Ninja ..
            ninja
